<?php use Lib\FlashMessage; ?>

<?php foreach (FlashMessage::get() as $type => $message): ?>
  <div class="alert-center">
    <div class="alert alert-<?= $type; ?>">
        <?= htmlspecialchars($message, ENT_QUOTES, 'UTF-8'); ?>
    </div>
  </div>
<?php endforeach; ?>
<head>
    <meta charset="UTF-8">
    <title>Admins</title>
    <link href="/assets/css/application.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<div class="container mt-5">
    <h1>Gerenciar Administradores</h1>
    <a href="/admin/create">Adicionar Novo Administrador</a>

    <table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Data de Nascimento</th>
            <th>Telefone</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($adminsWithLogin as $item): ?>
    <tr>
        <td><?= $item['admin']->id ?></td>
        <td><?= $item['admin']->name ?></td>
        <td><?= $item['login'] ? $item['login']->email : 'Sem login' ?></td>
        <td><?= $item['admin']->date_birth ?></td>
        <td><?= $item['admin']->phone ?></td>
        <td>
            <button class="btn btn-primary" onclick="window.location.href='/admin/edit/<?= $item['admin']->id ?>'">Editar</button>
            <form method="POST" action="/admin/delete/<?= $item['admin']->id ?>" style="display:inline;">
              <button type="submit" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja remover?')">Remover</button>
          </form>
        </td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
</div>
