<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Administrador</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Criar Novo Administrador</h1>

        <form action="/admin/create" method="POST">
            <div class="mb-3">
                <label for="name" class="form-label">Nome</label>
                <input type="text" class="form-control" id="name" name="name" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Senha</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <div class="mb-3">
              <label for="date_birth" class="form-label">Data de Nascimento:</label>
              <input type="date" class="form-control" id="date_birth" name="date_birth">
            </div>
            <div class="mb-3">
              <label for="phone" class="form-label">Telefone:</label>
              <input
                class="form-control"
                id="phone"
                name="phone"
                placeholder="(00)00000-0000"
                pattern="\(\d{2}\)\d{4,5}-\d{4}"
                title="O telefone deve estar no formato (XX)XXXXX-XXXX."
              >
            </div>
            <div class="mb-3">
              <button type="submit" class="btn btn-success">Criar Administrador</button>
              <a href="/admin/admins" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</body>
</html>
