<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Administrador</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container mt-5">
  <h1>Editar Administrador</h1>
  <form action="/admin/edit/<?= $admin->id ?>" method="POST">
  <div class="mb-3">
    <label for="name" class="form-label">Nome:</label>
    <input type="text" class="form-control" name="name" id="name" value="<?= $admin->name ?>" required>
  </div>
  <div class="mb-3">
    <label for="email" class="form-label">Email:</label>
    <input type="email" class="form-control" name="email" id="email" value="<?= $login ? $login->email : '' ?>" required>
  </div>
  <div class="mb-3">
    <label for="password" class="form-label">Senha:</label>
    <input type="password" class="form-control" name="password" id="password" required>
  </div>
  <div class="mb-3">
    <label for="date_birth" class="form-label">Data de Nascimento:</label>
    <input type="date" class="form-control" name="date_birth" id="date_birth" value="<?= $admin->date_birth ?>" required>
  </div>
  <div class="mb-3">
    <label for="phone" class="form-label">Telefone:</label>
    <input type="text" class="form-control" name="phone" id="phone" value="<?= $admin->phone ?>">
  </div>

  <button type="submit" class="btn btn-primary">Atualizar Administrador</button>
  <a href="/admin/admins" class="btn btn-secondary">Cancelar</a>
</form>

</div>
</body>
