<?php use Lib\FlashMessage; ?>

<?php foreach (FlashMessage::get() as $type => $message): ?>
  <div class="alert-center">
    <div class="alert alert-<?= $type; ?>">
        <?= htmlspecialchars($message, ENT_QUOTES, 'UTF-8'); ?>
    </div>
  </div>
<?php endforeach; ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Área do Admin</title>
    <link href="/assets/css/application.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="header">
        <h1>Área do Admin</h1>
        <a href="index.php?action=logout" class="logout-btn">Sair</a>
    </div>
  <div class="container mt-5">
    <div class="content">
        <p>Bem-vindo, Admin!</p>
        <h1>Painel do Administrador</h1>
        <button class="btn btn-primary" onclick="window.location.href='../admin/admins'">Gerenciar Administradores</button>
    </div>
    </div>
    <div>

  </div>

</body>
</html>
