<?php use Lib\FlashMessage; ?>

<?php foreach (FlashMessage::get() as $type => $message): ?>
  <div class="alert-center">
    <div class="alert alert-<?= $type; ?>">
        <?= htmlspecialchars($message, ENT_QUOTES, 'UTF-8'); ?>
    </div>
  </div>
<?php endforeach; ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>App</title>
    <link href="/assets/css/application.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <div class="header">
        <h1>Bem-vindo, Usuário!</h1>
        <a href="index.php?action=logout" class="logout-btn">Sair</a>
    </div>
    <div class="content">
      <div class="mt-3">
        <p>Bem-vindo!</p>
        <a href="profile" class="btn btn-secondary">perfil</a>
        </div>
    </div>

    <div class="mt-3">
      <a href="/tickets" class="btn btn-secondary">Meus Tickets</a>
    </div>
</div>
</body>
</html>

