<?php use Lib\FlashMessage; ?>

<?php foreach (FlashMessage::get() as $type => $message): ?>
  <div class="alert-center">
    <div class="alert alert-<?= $type; ?>">
        <?= htmlspecialchars($message, ENT_QUOTES, 'UTF-8'); ?>
    </div>
  </div>
<?php endforeach; ?>
<div class="container mt-5">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <h2 class="mb-4">Tickets</h2>
    <a href="/tickets/create" class="btn btn-success mb-3">Criar Novo Ticket</a>

  <table class="table table-striped table-bordered">
      <thead class="table-dark">
          <tr>
              <th>Título</th>
              <th>Status</th>
              <th>Prioridade</th>
              <th>Ações</th>
          </tr>
      </thead>
      <tbody>
          <?php foreach ($tickets as $ticket) : ?>
              <tr>
                  <td><?= $ticket->title ?></td>
                  <td><span class="badge bg-info"><?= $ticket->status()->name ?></span></td>
                  <td><span class="badge bg-warning"><?= $ticket->priority()->get()->name ?></span></td>
                  <td>
                      <a href="/tickets/<?= $ticket->id ?>" class="btn btn-secondary btn-sm">Ver</a>
                  </td>
              </tr>
          <?php endforeach; ?>
      </tbody>
  </table>
  <div class="mt-3">
            <a href="/user" class="btn btn-secondary">Voltar</a>
    </div>
</div>
