<div class="container mt-5">
  <h2 class="mb-4">Lista de Tickets</h2>
  <table class="table table-striped table-bordered">
      <thead class="table-dark">
          <tr>
              <th>ID</th>
              <th>Título</th>
              <th>Status</th>
              <th>Prioridade</th>
              <th>Ações</th>
          </tr>
      </thead>
      <tbody>
          <?php foreach ($tickets as $ticket) : ?>
              <tr>
                  <td><?= $ticket->id ?></td>
                  <td><?= $ticket->title ?></td>
                  <td><span class="badge bg-info"><?= $ticket->status()->name ?></span></td>
                  <td><span class="badge bg-warning"><?= $ticket->priority()->get()->name ?></span></td>
                  <td>
                      <?php if ($ticket->status_id == 1) : ?>
                          <form action="/admin/tickets/open/<?= $ticket->id ?>" method="POST">
                              <button type="submit" class="btn btn-primary btn-sm">Abrir Chamado</button>
                          </form>
                      <?php elseif ($ticket->status_id == 2) : ?>
                          <form action="/admin/tickets/close/<?= $ticket->id ?>" method="POST">
                              <button type="submit" class="btn btn-success btn-sm">Finalizar Chamado</button>
                          </form>
                      <?php endif; ?>
                  </td>
              </tr>
          <?php endforeach; ?>
      </tbody>
  </table>
  <div class="mt-3">
            <a href="/admin" class="btn btn-secondary">Voltar</a>
    </div>
</div>
